# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Create working directory
WORKDIR /app

# Copy requirements and project files
COPY pyproject.toml ./
COPY poetry.lock ./
COPY uv.lock ./
COPY README.md ./
COPY LICENSE ./
COPY src ./src
COPY tests ./tests
COPY assets ./assets

# Install pip dependencies
RUN pip install --upgrade pip \
    && pip install uv \
    && pip install .

# Expose MCP port if needed (usually not required for stdio transport)

# Use the MCP entrypoint
CMD ["osv-server"]
